"""Core tensor enumerator.

The reference frame F0 is a storage convention.  Every generated frame F_J is
named by a fixed matrix J from F0 to that frame.  A tensor is therefore not a
raw list of arrays, but a family of framed arrays:

    (F_J, transform(seed_components, J, tensor_type))

Convention: J transforms contravariant vector components from F0 to F_J.
Upper tensor indices use J; lower tensor indices use J^-1.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from itertools import count, islice, product
from typing import Iterable, Iterator, Sequence

Index = tuple[int, ...]
Matrix = tuple[tuple[Fraction, ...], ...]
Components = dict[Index, Fraction]


@dataclass(frozen=True)
class Frame:
    """A frame addressed by its component-change matrix from F0."""

    name: str
    from_reference: Matrix


@dataclass(frozen=True)
class TensorSeed:
    """One component array in the reference frame F0."""

    components: Components
    tensor_type: tuple[int, int]
    dimension: int


@dataclass(frozen=True)
class Representation:
    """One generated coordinate representation of the same tensor."""

    frame: Frame
    components: Components
    tensor_type: tuple[int, int]
    step: int | None = None


class TensorEnumerator:
    """Enumerate framed representations generated from one seed."""

    def __init__(self, seed: TensorSeed, matrices: Iterable[Matrix]):
        self.seed = seed
        self.matrices = matrices

    def __iter__(self) -> Iterator[Representation]:
        for step, j in enumerate(self.matrices):
            yield representation_at_matrix(self.seed, j, step=step)


def representation_at_matrix(
    seed: TensorSeed,
    j: Matrix,
    *,
    step: int | None = None,
) -> Representation:
    """Compute the representation generated by one matrix J."""

    name = f"F_{step}" if step is not None else "F_J"
    frame = Frame(name=name, from_reference=j)
    return Representation(
        frame=frame,
        components=transform_components(
            seed.components,
            seed.tensor_type,
            j,
            seed.dimension,
        ),
        tensor_type=seed.tensor_type,
        step=step,
    )


def representations_at_steps(
    seed: TensorSeed,
    matrices: Iterable[Matrix],
    steps: Iterable[int],
) -> Iterator[Representation]:
    """Run the enumerator only at selected global step numbers."""

    requested = set(steps)
    if not requested:
        return
    if min(requested) < 0:
        raise ValueError("step numbers must be non-negative")

    remaining = set(requested)
    for step, j in enumerate(matrices):
        if step in remaining:
            yield representation_at_matrix(seed, j, step=step)
            remaining.remove(step)
            if not remaining:
                return


def transform_components(
    components: Components,
    tensor_type: tuple[int, int],
    j: Matrix,
    dimension: int,
) -> Components:
    """Transform tensor components from F0 to F_J.

    For type (r, s), each upper index contributes a factor of J and each lower
    index contributes a factor of J^-1.
    """

    r, s = tensor_type
    rank = r + s
    j_inv = inverse(j)
    result: Components = {}

    for target in product(range(dimension), repeat=rank):
        total = Fraction(0)

        for source, value in components.items():
            factor = Fraction(1)

            for slot in range(r):
                factor *= j[target[slot]][source[slot]]

            for slot in range(r, rank):
                factor *= j_inv[source[slot]][target[slot]]

            total += factor * value

        if total:
            result[target] = total

    return result


def transition_between(source: Frame, target: Frame) -> Matrix:
    """The forced component-change matrix from one generated frame to another."""

    return matmul(target.from_reference, inverse(source.from_reference))


def enumerate_glq(dimension: int, *, max_height: int | None = None) -> Iterator[Matrix]:
    """Enumerate invertible rational matrices in GL(n, Q).

    A rational number is reached by height:

        height(a / b) = max(abs(a), b), with gcd(a, b) = 1 and b > 0

    Matrices are then reached by the maximum height of their entries. This is a
    real enumeration of GL(n, Q), although only finite prefixes are practical.
    """

    heights = range(1, max_height + 1) if max_height is not None else count(1)

    yielded: set[Matrix] = set()
    for height in heights:
        rationals = rationals_with_height_at_most(height)
        for flat in product(rationals, repeat=dimension * dimension):
            if all(rational_height(x) < height for x in flat):
                continue

            j = tuple(
                tuple(flat[i * dimension + k] for k in range(dimension))
                for i in range(dimension)
            )
            if j not in yielded and det(j) != 0:
                yielded.add(j)
                yield j


def enumerate_glnz(dimension: int, *, max_abs: int | None = None) -> Iterator[Matrix]:
    """Enumerate invertible integer matrices, a readable subset of GL(n, Q).

    This is intentionally modest: it is readable and good for demonstrations.
    Increasing `max_abs` produces a finite prefix; leaving it unset keeps
    widening the integer search box forever.
    """

    boxes = range(1, max_abs + 1) if max_abs is not None else count(1)

    yielded: set[Matrix] = set()
    identity = tuple(
        tuple(Fraction(1 if i == k else 0) for k in range(dimension))
        for i in range(dimension)
    )
    yielded.add(identity)
    yield identity

    for bound in boxes:
        entries = range(-bound, bound + 1)
        for flat in product(entries, repeat=dimension * dimension):
            if all(abs(x) != bound for x in flat):
                continue

            j = tuple(
                tuple(Fraction(flat[i * dimension + k]) for k in range(dimension))
                for i in range(dimension)
            )
            if j not in yielded and det(j) != 0:
                yielded.add(j)
                yield j


def find_matrix_step(matrices: Iterable[Matrix], target: Matrix) -> tuple[int, Matrix]:
    """Return the first enumeration step where `target` appears."""

    for step, j in enumerate(matrices):
        if j == target:
            return step, j
    raise ValueError("target matrix was not found in the finite enumeration")


def inverse(matrix: Matrix) -> Matrix:
    """Invert a rational matrix with Gauss-Jordan elimination."""

    n = len(matrix)
    rows = [
        list(matrix[i]) + [Fraction(1 if i == k else 0) for k in range(n)]
        for i in range(n)
    ]

    for col in range(n):
        pivot = next((row for row in range(col, n) if rows[row][col]), None)
        if pivot is None:
            raise ValueError("matrix is not invertible")

        rows[col], rows[pivot] = rows[pivot], rows[col]
        scale = rows[col][col]
        rows[col] = [value / scale for value in rows[col]]

        for row in range(n):
            if row == col:
                continue
            factor = rows[row][col]
            if factor:
                rows[row] = [
                    value - factor * pivot_value
                    for value, pivot_value in zip(rows[row], rows[col])
                ]

    return tuple(tuple(row[n:]) for row in rows)


def matrix(values: Sequence[Sequence]) -> Matrix:
    """Convert a nested sequence to a rational matrix."""

    return tuple(tuple(Fraction(value) for value in row) for row in values)


def rationals_with_height_at_most(height: int) -> tuple[Fraction, ...]:
    """Return all rationals with height at most `height`, in stable order."""

    values = {Fraction(0)}
    for denominator in range(1, height + 1):
        for numerator in range(-height, height + 1):
            values.add(Fraction(numerator, denominator))

    return tuple(sorted(values, key=lambda x: (rational_height(x), x.denominator, x)))


def rational_height(value: Fraction) -> int:
    """Height of a reduced rational number."""

    return max(abs(value.numerator), value.denominator)


def matmul(a: Matrix, b: Matrix) -> Matrix:
    """Multiply rational matrices."""

    rows = len(a)
    cols = len(b[0])
    inner = len(b)
    return tuple(
        tuple(sum(a[i][k] * b[k][j] for k in range(inner)) for j in range(cols))
        for i in range(rows)
    )


def det(matrix: Matrix) -> Fraction:
    """Compute a rational determinant by elimination."""

    n = len(matrix)
    rows = [list(row) for row in matrix]
    sign = Fraction(1)
    value = Fraction(1)

    for col in range(n):
        pivot = next((row for row in range(col, n) if rows[row][col]), None)
        if pivot is None:
            return Fraction(0)
        if pivot != col:
            rows[col], rows[pivot] = rows[pivot], rows[col]
            sign *= -1

        pivot_value = rows[col][col]
        value *= pivot_value
        for row in range(col + 1, n):
            factor = rows[row][col] / pivot_value
            rows[row] = [
                x - factor * y for x, y in zip(rows[row], rows[col])
            ]

    return sign * value


def as_sparse(values: Sequence, *, rank: int) -> Components:
    """Convert a nested Python sequence to sparse component storage."""

    result: Components = {}

    def visit(prefix: Index, item) -> None:
        if len(prefix) == rank:
            value = Fraction(item)
            if value:
                result[prefix] = value
            return
        for i, child in enumerate(item):
            visit(prefix + (i,), child)

    visit((), values)
    return result


def as_dense(components: Components, dimension: int, rank: int):
    """Convert sparse component storage back to nested lists."""

    if rank == 0:
        return components.get((), Fraction(0))

    def build(prefix: Index):
        if len(prefix) == rank:
            return components.get(prefix, Fraction(0))
        return [build(prefix + (i,)) for i in range(dimension)]

    return build(())


def first(iterable: Iterable[Matrix], n: int) -> list[Matrix]:
    """Small helper for examples and tests."""

    return list(islice(iterable, n))
